plugins:
  # to see sitemap, use /sitemap.xml
  - jekyll-sitemap
  - jekyll-include-cache

# exclude: [_creators, _sass, _data, _includes, _layouts, assets, scripts, _posts]

# theme: minimal-mistakes-jekyll
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

collections:
  creators:
    output: true
  projects:
    output: true

# Now don't need to include layout: ____ in every file
defaults:
  - scope:
      path: ""
      type: "creators"
    values:
      layout: "creator"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
